remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache


title: Trond Hindenes
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hindenes.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: trondhindenes

author:
  name: "Trond Hindenes"

# Build settings
markdown: kramdown

